
name: linked_scroll_controller
version: 0.2.0
description: >
  A scroll controller that allows two or more scroll views to be in sync.
repository: https://github.com/google/flutter.widgets/tree/master/packages/linked_scroll_controller

environment:
  sdk: '3.5.4'
  flutter: '>=1.13.8'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0-0
  flutter_test:
    sdk: flutter
