name: scrollable_positioned_list_example

publish_to: 'none'

environment:
  sdk: '3.5.4'
  flutter: '>=1.13.8'

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter